[workspace]
resolver = "3"
members = [
    "rust_lib_kata",
    "automicon",
    "kata_server",
]


[workspace.package]
rust-version = "1.98.1"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(osslconf, values("OPENSSL_NO_BF"))',
    'cfg(osslconf, values("OPENSSL_NO_CAMELLIA"))',
    'cfg(osslconf, values("OPENSSL_NO_CAST"))',
    'cfg(osslconf, values("OPENSSL_NO_IDEA"))',
    'cfg(osslconf, values("OPENSSL_NO_OCB"))',
    'cfg(osslconf, values("OPENSSL_NO_DES"))',
] }

[profile.release]
debug = true



[workspace.lints.clippy]
# default clippy lint levels matching the common-ci environment:
# https://gitlab.com/sequoia-pgp/common-ci/-/blob/main/templates/precheck.yml
suspicious = { level = "deny", priority = -1 }
style = { level = "allow", priority = -1 }
complexity = { level = "allow", priority = -1 }

# The Rust Crypto crates are *very* slow when compiled without any
# optimizations.  Turn on some optimizations.
[profile.dev.package.aes]
opt-level = 2
[profile.dev.package.aes-gcm]
opt-level = 2
[profile.dev.package.argon2]
opt-level = 2
[profile.dev.package.blake2]
opt-level = 2
[profile.dev.package.block-padding]
opt-level = 2
[profile.dev.package.blowfish]
opt-level = 2
[profile.dev.package.camellia]
opt-level = 2
[profile.dev.package.cast5]
opt-level = 2
[profile.dev.package.cipher]
opt-level = 2
[profile.dev.package.cfb-mode]
opt-level = 2
[profile.dev.package.cx448]
opt-level = 2
[profile.dev.package.des]
opt-level = 2
[profile.dev.package.digest]
opt-level = 2
[profile.dev.package.dsa]
opt-level = 2
[profile.dev.package.eax]
opt-level = 2
[profile.dev.package.ecb]
opt-level = 2
[profile.dev.package.ecdsa]
opt-level = 2
[profile.dev.package.ed25519]
opt-level = 2
[profile.dev.package.ed25519-dalek]
opt-level = 2
[profile.dev.package.idea]
opt-level = 2
[profile.dev.package.keccak]
opt-level = 2
[profile.dev.package.md-5]
opt-level = 2
[profile.dev.package.num-bigint-dig]
opt-level = 2
[profile.dev.package.num-integer]
opt-level = 2
[profile.dev.package.ocb3]
opt-level = 2
[profile.dev.package.p256]
opt-level = 2
[profile.dev.package.p384]
opt-level = 2
[profile.dev.package.p521]
opt-level = 2
[profile.dev.package.ripemd]
opt-level = 2
[profile.dev.package.rsa]
opt-level = 2
[profile.dev.package.sha2]
opt-level = 2
[profile.dev.package.sha3]
opt-level = 2
[profile.dev.package.twofish]
opt-level = 2
[profile.dev.package.x25519-dalek]
opt-level = 2
